config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # resources :students

  namespace :admin do 
    resources :students
    resources :projects
    resources :courses
    resources :blogs
    get 'dashboard' => 'dashboard#index'
  end
end

app/models/student.rb
class Student < ApplicationRecord
  paginates_per 10
  has_one_attached :profile_image
  
  has_many :blogs
  has_and_belongs_to_many :courses
  has_many :student_projects
  has_many :projects, through: :student_projects
  
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates :first_name, :last_name, length: { minimum: 2, maximum: 50 }
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: 'only letters are allowed' }

  validate :validate_student_age

  after_commit :display_student_age

  def display_student_age
    if self.date_of_birth.present?
      age = Date.today.year - self.date_of_birth.year
      puts "===========Age of the student is #{age}==========="
    else
      puts "===========Age can not be calculated without date_of_birth==========="
    end
  end

  def validate_student_age
    if self.date_of_birth.present?
      age = Date.today.year - self.date_of_birth.year
      if age < 15
        errors.add(:age, ' please provide a valid date of birth here. Age must be greater than 15')
      end
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
    return nil unless date_of_birth.present?
    
    return Date.today.year - date_of_birth.year
  end

  def name_with_email
    "#{full_name} / #{email}"
  end

end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < AdminController
  include ApplicationHelper
  before_action :set_student, only: %i[show edit update destroy]
  helper_method :formatted_date

  def index
    @q = Student.ransack(params[:q])
    @students = @q.result(distinct: true).page(params[:page])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to admin_students_path, notice: 'Student has been created successfully'
    else
      render :new
    end
  end

  def show
  end

  def edit
    date = formatted_date(@student.date_of_birth)
  end

  def update
    if @student.update(student_params)
      redirect_to admin_student_path(@student), notice: 'Student has been updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to admin_students_path, notice: 'Student has been deleted successfully'
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :permanent_address, :local_address, :permanent_contact_number, :alternate_contact_number, :profile_image)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def formatted_date(date)
    date.strftime('%A, %b %d, %Y')
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout 'admin'
  include ApplicationHelper
  before_action :set_student, only: %i[show edit update destroy]
  helper_method :formatted_date

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: 'Student has been created successfully'
    else
      render :new
    end
  end

  def show
  end

  def edit
    date = formatted_date(@student.date_of_birth)
  end

  def update
    if @student.update(student_params)
      redirect_to student_path(@student), notice: 'Student has been updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, notice: 'Student has been deleted successfully'
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :permanent_address, :local_address, :permanent_contact_number, :alternate_contact_number)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def formatted_date(date)
    date.strftime('%A, %b %d, %Y')
  end

end

app/views/admin/students/_form.html.erb
<%= form_with(model: [:admin, student]) do |form| %>

  <% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control form-control-lg" %>
  </div>

  <div>
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :permanent_address %>
    <%= form.text_field :permanent_address, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :local_address %>
    <%= form.text_field :local_address, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :permanent_contact_number %>
    <%= form.text_field :permanent_contact_number, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :alternate_contact_number %>
    <%= form.text_field :alternate_contact_number, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :profile_image %><br>
    <%= form.file_field :profile_image %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/admin/students/_search_form.html.erb
<div class="card rounded-0">
  <div class="card-body">
    <%= search_form_for q, url: :admin_students do |form| %>
      <div class="form-group row">
        <div class="col-lg-3">
          <%= form.label :first_name %>
          <%= form.text_field :first_name_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :last_name %>
          <%= form.text_field :last_name_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :email %>
          <%= form.text_field :email_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :permanent_contact_number %>
          <%= form.text_field :permanent_contact_number_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :alternate_contact_number %>
          <%= form.text_field :alternate_contact_number_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :local_address %>
          <%= form.text_field :local_address_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :permanent_address %>
          <%= form.text_field :permanent_address_cont, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
        <%= link_to "Reset", admin_students_path, class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/students/edit.html.erb
<div class="col-lg-8">
  <h1>Edit Student</h1>

  <%= render "form", student: @student %>
</div>

app/views/admin/students/index.html.erb
<p><%= notice %></p>
<div class="col-lg-12">
  <%= render "admin/students/search_form", q: @q %>
  <h1>Listing Students</h1>
  <%= link_to 'New Student', new_admin_student_path, class: "btn btn-primary btn-lg mb-3" %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Student</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name_with_email %></td>
          <td>
            <%= link_to 'View', admin_student_path(student), class: "btn btn-primary btn-sm" %>
            <%= link_to 'Edit', edit_admin_student_path(student), class: "btn btn-warning btn-sm" %>
            <%= link_to 'Delete', admin_student_path(student), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>    
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @students %>
</div>

app/views/admin/students/new.html.erb
<div class="col-lg-8">
  <h1>New Student</h1>

  <%= render "form", student: @student %>
</div>

app/views/admin/students/show.html.erb
<div class="col-lg-10">
  <div class="card rounded-0 shadow mt-5 mb-5">
    <div class="card-body">
      <% if @student.profile_image.attached? %>
        <%= image_tag @student.profile_image, style: "width: 200px;height:300px;" %>
      <% end %>
      <p><%= notice %></p>
      <h1>Student Details</h1>

      <p><strong>Name: </strong> <%= @student.full_name %></p>

      <p><strong>Email: </strong><%= @student.email %></p>

      <p><strong>Date of Birth: </strong><%= formatted_date(@student.date_of_birth) %></p>

      <p><strong>Age: </strong><%= @student.age %></p>

      <p><strong>Permanent Address: </strong><%= @student.permanent_address %></p>
      <p><strong>Local Address: </strong><%= @student.local_address %></p>
      <p><strong>Permanent Contact: </strong><%= @student.permanent_contact_number %></p>
      <p><strong>Alternate Contact: </strong><%= @student.alternate_contact_number %></p>

      <%= link_to 'Back', admin_students_path, class: "btn btn-primary" %>
      <%= link_to 'Edit', edit_admin_student_path(@student), class: "btn btn-secondary" %>
    </div>
  </div>
</div>