config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # resources :students

  namespace :admin do 
    resources :students
    resources :projects
    resources :courses
    resources :blogs
    get 'dashboard' => 'dashboard#index'
  end
end

app/views/shared/_admin_footer.html.erb
<footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>

app/views/shared/_admin_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
      aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">

  <!-- Nav Item - Search Dropdown (Visible Only XS) -->
  <li class="nav-item dropdown no-arrow d-sm-none">
    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-search fa-fw"></i>
  </a>
  <!-- Dropdown - Messages -->
  <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
  aria-labelledby="searchDropdown">
  <form class="form-inline mr-auto w-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small"
      placeholder="Search for..." aria-label="Search"
      aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>
</div>
</li>

<!-- Nav Item - Alerts -->
<li class="nav-item dropdown no-arrow mx-1">
  <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <i class="fas fa-bell fa-fw"></i>
  <!-- Counter - Alerts -->
  <span class="badge badge-danger badge-counter">3+</span>
</a>
<!-- Dropdown - Alerts -->
<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
aria-labelledby="alertsDropdown">
<h6 class="dropdown-header">
  Alerts Center
</h6>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="mr-3">
    <div class="icon-circle bg-primary">
      <i class="fas fa-file-alt text-white"></i>
    </div>
  </div>
  <div>
    <div class="small text-gray-500">December 12, 2019</div>
    <span class="font-weight-bold">A new monthly report is ready to download!</span>
  </div>
</a>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="mr-3">
    <div class="icon-circle bg-success">
      <i class="fas fa-donate text-white"></i>
    </div>
  </div>
  <div>
    <div class="small text-gray-500">December 7, 2019</div>
    $290.29 has been deposited into your account!
  </div>
</a>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="mr-3">
    <div class="icon-circle bg-warning">
      <i class="fas fa-exclamation-triangle text-white"></i>
    </div>
  </div>
  <div>
    <div class="small text-gray-500">December 2, 2019</div>
    Spending Alert: We've noticed unusually high spending for your account.
  </div>
</a>
<a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
</div>
</li>

<!-- Nav Item - Messages -->
<li class="nav-item dropdown no-arrow mx-1">
  <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <i class="fas fa-envelope fa-fw"></i>
  <!-- Counter - Messages -->
  <span class="badge badge-danger badge-counter">7</span>
</a>
<!-- Dropdown - Messages -->
<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
aria-labelledby="messagesDropdown">
<h6 class="dropdown-header">
  Message Center
</h6>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="dropdown-list-image mr-3">
    <%= image_tag "undraw_profile_1.svg", class: "rounded-circle" %>
    <div class="status-indicator bg-success"></div>
  </div>
  <div class="font-weight-bold">
    <div class="text-truncate">Hi there! I am wondering if you can help me with a
    problem I've been having.</div>
    <div class="small text-gray-500">Emily Fowler · 58m</div>
  </div>
</a>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="dropdown-list-image mr-3">
    <img class="rounded-circle" src="img/undraw_profile_2.svg"
    alt="...">
    <div class="status-indicator"></div>
  </div>
  <div>
    <div class="text-truncate">I have the photos that you ordered last month, how
    would you like them sent to you?</div>
    <div class="small text-gray-500">Jae Chun · 1d</div>
  </div>
</a>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="dropdown-list-image mr-3">
    <img class="rounded-circle" src="img/undraw_profile_3.svg"
    alt="...">
    <div class="status-indicator bg-warning"></div>
  </div>
  <div>
    <div class="text-truncate">Last month's report looks great, I am very happy with
    the progress so far, keep up the good work!</div>
    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
  </div>
</a>
<a class="dropdown-item d-flex align-items-center" href="#">
  <div class="dropdown-list-image mr-3">
    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
    alt="...">
    <div class="status-indicator bg-success"></div>
  </div>
  <div>
    <div class="text-truncate">Am I a good boy? The reason I ask is because someone
    told me that people say this to all dogs, even if they aren't good...</div>
    <div class="small text-gray-500">Chicken the Dog · 2w</div>
  </div>
</a>
<a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
</div>
</li>

<div class="topbar-divider d-none d-sm-block"></div>

<!-- Nav Item - User Information -->
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
  <%= image_tag "undraw_profile.svg", class: "img-profile" %>
</a>
<!-- Dropdown - User Information -->
<div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
aria-labelledby="userDropdown">
<a class="dropdown-item" href="#">
  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
  Profile
</a>
<a class="dropdown-item" href="#">
  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
  Settings
</a>
<a class="dropdown-item" href="#">
  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
  Activity Log
</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
  Logout
</a>
</div>
</li>

</ul>

</nav>

app/views/shared/_admin_logout_modal.html.erb
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <%= link_to "Logout", destroy_admin_user_session_path, method: :delete, class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    </div>

app/views/shared/_admin_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <%= link_to admin_dashboard_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-users"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Student Management</div>
  <% end %>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <%= link_to admin_dashboard_path, class: "nav-link" do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
    <% end %>
  </li>

    <!-- Divider -->
  <hr class="sidebar-divider">

    <!-- Heading -->
  <div class="sidebar-heading">
    Interface
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
    aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Resources</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to "Students", admin_students_path, class: "collapse-item" %>
        <%= link_to "Courses", admin_courses_path, class: "collapse-item" %>
        <%= link_to "Projects", admin_projects_path, class: "collapse-item" %>
        <%= link_to "Blogs", admin_blogs_path, class: "collapse-item" %>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

<style>
  .footer {
    background-color: #f5f5f5;
  }
</style>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Student Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">

        <% if admin_user_signed_in? %>
          <%= link_to "Sign Out", destroy_admin_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign In", new_admin_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>