config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    registrations: 'admin_users/registrations',
    passwords: 'admin_users/passwords',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # resources :students

  namespace :admin do 
    resources :students
    resources :projects
    resources :courses
    resources :blogs
    get 'dashboard' => 'dashboard#index'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  paginates_per 10
  include Validatable
  has_many :student_projects
  has_many :students, through: :student_projects
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).page(params[:page])
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to admin_project_path(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to admin_project_path(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_with(model: [:admin, project]) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary btn-lg" %>
    <%= link_to 'Back', admin_projects_path, class: "btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/admin/projects/_search_form.html.erb
<div class="card rounded-0">
  <div class="card-body">
    <%= search_form_for q, url: :admin_projects do |form| %>
      <div class="form-group row">
        <div class="col-lg-3">
          <%= form.label :name %>
          <%= form.text_field :name_cont, class: "form-control" %>
        </div>
        <div class="col-lg-3">
          <%= form.label :description %>
          <%= form.text_field :description_cont, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
        <%= link_to "Reset", admin_projects_path, class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/admin/projects/index.html.erb
<%= render "admin/students/search_form", q: @q %>
<h1>Projects</h1>
<%= link_to 'New Project', new_admin_project_path, class: "btn btn-primary btn-lg mb-3" %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td>
          <%= link_to 'Show', admin_project_path(project), class: "btn btn-primary btn-sm" %>
          <%= link_to 'Edit', edit_admin_project_path(project), class: "btn btn-warning btn-sm" %>
          <%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @projects %>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

app/views/admin/projects/show.html.erb
<div class="col-lg-12 mb-5">
  <div class="card rounded-0 shadow">
    <div class="card-body">
      <p>
        <strong>Name:</strong>
        <%= @project.name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @project.description %>
      </p>

      <%= link_to 'Edit', edit_admin_project_path(@project), class: "btn btn-primary btn-lg" %> 
      <%= link_to 'Back', admin_projects_path, class: "btn btn-outline-primary btn-lg" %>
    </div>
  </div>
</div>